version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    ports:
      - '3000:3000'
    volumes:
      - .:/app/
    stdin_open: true
    network_mode: bridge
